<?php

namespace app\classes;

use WebSocket\Exception;
use yii\log\Logger;
use yii\rest\ActiveController;
use WebSocket\Client;
use yii\web\HttpException;

/**
 * Created by PhpStorm.
 * User: earedrodent
 * Date: 15.01.2019
 * Time: 11:35
 */

/**
 * Class WebSocketInformer
 * @package app\wsc
 * Эти действия не могут изменить данные
 * @property $ignoreActions
 */
class NuxtRestApiController extends ActiveController
{
    protected $wssUrl = 'ws://127.0.0.1:6002';
    protected $_modifiedTables = [];
    protected $modifiedTables = [];
    protected $_ignoreModifiedTables = ['index', 'view', 'options'];
    protected $ignoreModifiedTables = [];
    protected $transaction;


    public function afterAction($action, $result)
    {
        $restAction = $action->id;

        if (!in_array($restAction, array_merge($this->_ignoreModifiedTables, $this->ignoreModifiedTables))) {
            $modifiedDefault = isset($this->modifiedTables['default']) && is_array($this->modifiedTables['default'])
                ? $this->modifiedTables['default']
                : [];
            $modifiedByAction = isset($this->modifiedTables[$restAction]) && is_array($this->modifiedTables[$restAction])
                ? $this->modifiedTables[$restAction]
                : [];
            $this->_modifiedTables = array_merge($modifiedDefault, $modifiedByAction);

            $wsc = new Client($this->wssUrl);
            $wsc->send(json_encode($this->_modifiedTables));
        }
        return parent::afterAction($action, $result);
    }

    public function runAction($id, $params = [])
    {
        $this->transaction = \Yii::$app->db->beginTransaction();
        try {
            $result = parent::runAction($id, $params); // TODO: Change the autogenerated stub
            $this->transaction->commit();
            return $result;
        } catch (HttpException $e) {
            $this->transaction->rollBack();
            throw new HttpException($e->statusCode,'Transaction rolled back. ' . $e->getMessage());
        }
    }
}