<?php
/**
 * Created by PhpStorm.
 * User: earedrodent
 * Date: 13.12.2018
 * Time: 12:13
 */

namespace app\modules\v1\controllers;

use app\models\DBUser;
use yii\web\ServerErrorHttpException;
use yii\rest\ActiveController;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\AccessControl;
use Yii;

/**
 * Типы разрешений
 * - роль     (ROLE_...)
 * - страница (PAGE_...)
 * - rest api (API_...)
 * -
 *
 *
 * Class RoleManagerController
 * @package app\modules\v1\controllers
 */
class RoleController extends ActiveController
{
    public $modelClass = 'app\modules\v1\models\User';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className()
        ];
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [[
                'actions' => ['browse-roles', 'create', 'update', 'delete'],
                'allow' => true,
                'roles' => ['API_V1_RoleManager']
            ]
            ]
        ];
        return $behaviors; // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions = parent::actions();
        return $actions; // TODO: Change the autogenerated stub
    }

    public function actionBrowseRoles()
    {
        $roles = Yii::$app->authManager->getRoles();
        $roleNames = [];
        foreach ($roles as $role) {
            $roleNames[] = $role->name;
        }

        $rolesExtended = [];
        foreach ($roleNames as $roleName) {
            $permissionsEx = [];
            foreach (Yii::$app->authManager->getPermissionsByRole($roleName) as $permissionEx) {
                $permissionsEx[] = ['name' => $permissionEx->name];
            }
            $rolesEx = [];
            foreach (Yii::$app->authManager->getChildRoles($roleName) as $roleEx) {
                if ($roleEx->name !== $roleName) {
                    $rolesEx[] = ['name' => $roleEx->name];
                }
            }
            $rolesExtended[] = [
                'name' => $roleName,
                'permissions' => $permissionsEx,
                'roles' => $rolesEx,
            ];
        }
        return $rolesExtended;
    }
}