<?php
/**
 * Created by PhpStorm.
 * User: EaredRodent
 * Date: 2/11/2019
 * Time: 09:54 PM
 */

namespace app\modules\v1\controllers;

use app\modules\v1\models\Downloads;
use http\Env\Response;
use Yii;
use yii\httpclient\Client;
use yii\filters\AccessControl;
use yii\filters\auth\HttpBearerAuth;
use yii\httpclient\Request;
use yii\rest\ActiveController;
use yii\web\HttpException;

class StartUpController extends ActiveController
{
    public $modelClass = '';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => ['index', 'download']
        ];
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'actions' => ['index', 'download'],
                    'allow' => true,
                    'roles' => ['?', '@']
                ]
            ]
        ];
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        Yii::$app->response->headers->set('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Cookie, Authorization');
        Yii::$app->response->headers->set('Access-Control-Allow-Credentials', 'true');
        Yii::$app->response->headers->set('Access-Control-Allow-Origin', '*');
        Yii::$app->response->headers->set('Access-Control-Expose-Headers', 'Log-Dbcount, Log-Dbtime, Log-Apptime, Log-Appmemory');
        return parent::afterAction($action, $result);
    }

    public function actionIndex()
    {
        return [
            'version' => '0.3.2',
            'dso_quicklauncher' => '0.3.2',
            'dso_cam' => ['core_version' => '4.1.3', 'version' => '4.1.3'],
            'migration' => ['version' => 'dso_quicklauncher']
        ];
    }

    public function actionDownload()
    {
        $downloads = new Downloads();
        $downloads->save();
    }
}

?>
