<?php
/**
 * Created by PhpStorm.
 * User: alexander
 * Date: 04.12.2018
 * Time: 19:06
 */

namespace app\modules\v1;

class Module extends \yii\base\Module
{
	function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}
}